# Writes scores to the out/ directory
name: Scores

on:
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lua-version: [5.1, 5.2, 5.3]

    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # CLI arguments
          args: --check .