# Ensures functionality of benchmark after every commit
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lua-version: [5.1, 5.2, 5.3]

    steps:
      - uses: actions/checkout@v3
      - name: Install Lua
        run: |
          sudo apt install lua${{ matrix.lua-version }}
      - name: Run Benchmark
        run: |
          lua SimpleBench.lua
  test-luau:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Unzip
        run: |
          sudo apt install unzip
      - name: Download Luau
        run: |
          curl -L -i --output luau.zip https://github.com/Roblox/luau/releases/latest/download/luau-ubuntu.zip
      - name: Unpack Luau
        run: |
          echo "unzip -o -d luau luau.zip; echo done" > extract.sh
          chmod +x extract.sh
          ./extract.sh
          rm extract.sh
      - name: Run Benchmark
        run: |
          chmod +x luau/luau
          luau/luau SimpleBench.lua
