# Ensures functionality of benchmark after every commit
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lua-version: [5.1, 5.2, 5.3]

    steps:
      - uses: actions/checkout@v3
      - name: Install Lua
        run: |
          sudo apt install lua${{ matrix.lua-version }}
      - name: Run Benchmark
        run: |
          lua SimpleBench.lua
  test-luau:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Unzip
        run: |
          sudo apt install unzip
      - name: Get Luau
        run: |
          curl -O luau.zip https://github.com/Roblox/luau/releases/download/0.528/luau-ubuntu.zip
          unzip luau.zip -d luau
      - name: Run Benchmark
        run: |
          lua SimpleBench.lua
