# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lua-version: ['50', 5.1, 5.2, 5.3, 5.4]

    steps:
      - uses: actions/checkout@v3
      - name: Install Lua
        run: |
          sudo apt install lua${{ matrix.lua-version }}
      - name: Run Benchmark
        run: |
          lua SimpleBench.lua
